import type {Metadata} from "next";

import "./globals.css";

import {Instagram} from "lucide-react";

import {montserrat} from "@/fonts";
import {cn} from "@/lib/utils";
import {Header} from "@/components/header";
import {ColiFooter} from "@/components/coli-footer";
import {HeroV2} from "@/components/hero-v2";
import {Hero} from "@/components/hero";

export const metadata: Metadata = {
  title: "jad-marmoleria",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className="border-border bg-background text-foreground">
        <div
          className={cn(
            montserrat.className,
            "relative grid min-h-[100dvh] grid-rows-[auto,1fr] antialiased",
          )}
        >
          <Header />
          <main>{children}</main>
          {/* <div className="border-t">
            <ColiFooter />
          </div> */}
        </div>
      </body>
    </html>
  );
}
