import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";
import {Layers3} from "lucide-react";

import {montserrat} from "@/fonts";
import {cn} from "@/lib/utils";
import {Nav} from "@/components/nav-menu";

export const metadata: Metadata = {
  title: "jad-marmoleria",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className="border-border bg-background text-foreground">
        <div
          className={cn(
            montserrat.className,
            "container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] border-l border-r border-foreground font-sans antialiased",
          )}
        >
          <header className="inline-flex w-full justify-between border-b border-foreground text-xl font-bold leading-[4rem]">
            <Link className="ms-4 inline-flex items-center gap-3" href="/">
              <Layers3 className="size-8 text-foreground" />
              JAD Marmoleria
            </Link>
            <Nav />
          </header>
          <main className="px-4 py-8">{children}</main>
          <footer className="text-center leading-[4rem] opacity-70">
            © {new Date().getFullYear()} jad-marmoleria
          </footer>
        </div>
      </body>
    </html>
  );
}
